apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer  # Exposes service with an external IP (on AWS, GCP, etc.)
  selector:
    app: streamlit-app
  ports:
    - port: 80        # Exposes service on port 80 (standard HTTP)
      targetPort: 8501  # Streamlit runs on 8501 inside the container