version: '3.8'
services:
  web:
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    build:
        context: .
        dockerfile: Dockerfile_web
  app:
    volumes:
        - .:/app
    ports:
        - 8501:8501
    image: yourstreamlitapp:latest
    build:
        context: .
        dockerfile: Dockerfile_streamlit