apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: fast-api-back-end
          image: $AWS_ECR_REGISTRY/fastapi_llm_la:v0.0.4
          ports:
            - containerPort: 8000